name: CI/CD

on:
  push:
    branches: ['**']

jobs:
  pipeline:
    uses: patelronak/myworkflows/.github/workflows/pipeline.yml@main
    with:
      deploy-target: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
